# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/koa-boilerplate
  docker:
    - image: circleci/node:8.5

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      # run tests!
      - run: yarn test
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: echo 'DEPLOY NOT IMPLEMENTED'
workflows:
  version: 2
  workflow:
      jobs:
        - build
        - test:
            requires:
              - build
        - lint:
            requires:
              - build
        - deploy:
            requires:
              - test
              - lint
